load("@rules_python//sphinxdocs:sphinx.bzl", "sphinx_build_binary", "sphinx_docs")
load("@rules_python//sphinxdocs:sphinx_docs_library.bzl", "sphinx_docs_library")

load(
    "@rules_latex//latex:defs.bzl",
    "latex_document",
    "latex_library",
    "latex_test",
)

package(default_visibility = ["//visibility:public"])

sphinx_docs_library(
    name = "docs",
    srcs = [
        "index.rst",
	"more.png",
    ],
)

sphinx_build_binary(
    name = "sphinx",
    deps = [
        "@pypi//sphinx",
    ],
)

sphinx_docs(
    name = "3705",
    config = "conf.py",
    formats = ["latex"],
    sphinx = ":sphinx",
    deps = [
        ":docs",
    ],
    allow_persistent_workers = False,
    extra_opts = [
        "--fail-on-warning",
    ],
)

latex_document(
    name = "latex",
    main = "tex/3705.tex",
    srcs = glob(["tex/*"]),
    # deps = [":preamble"],
    # biber = True              # for biblatex documents
    # ctan_packages = ["..."]   # for packages not in the bundle
    reproducible = True,       # byte-identical PDF across builds
    # synctex = True            # PDF clicks copy <file>:<line> to clipboard
)
