module(name = "issue_3705")

bazel_dep(name = "rules_python", version = "1.9.0")
python = use_extension("@rules_python//python/extensions:python.bzl", "python")
python.defaults(python_version = "3.12")
python.toolchain(python_version = "3.12")
pip = use_extension("@rules_python//python/extensions:pip.bzl", "pip")
pip.parse(
    hub_name = "pypi",
    python_version = "3.12",
    requirements_lock = "//:pypi.lock",
)
use_repo(pip, "pypi")

bazel_dep(name = "rules_latex")
git_override(
    module_name = "rules_latex",
    remote = "https://github.com/nicklambourne/rules_latex",
    commit = "05b25f37003d262239e6115a9adf7b690553fe80",
)
tectonic = use_extension("@rules_latex//latex/toolchain:extensions.bzl", "tectonic")
tectonic.toolchain()
use_repo(tectonic, "rules_latex_tectonic_toolchains")
register_toolchains("@rules_latex_tectonic_toolchains//:all")
